#!/usr/bin/env python3
"""
Author : abennett1 <abennett1@localhost>
Date   : 2021-11-29
Purpose: A fun number guessing game
"""

import random


# --------------------------------------------------
def main():
    """Make a jazz noise here"""

    print('\nThis is a game in which you have to correctly guess'
          'the number randomly generated by the program.\n')
    ran_num = random.randint(1, 100)
    attempt = 1
    guess = int(input('Enter a number from 1 through 100: '))

    while guess != ran_num:
        if guess < ran_num:
            print(guess, 'is too small\n')
            attempt += 1
            guess = guess = int(input('Enter a number from 1 through 100: '))
        if guess > ran_num:
            print(guess, 'is too large\n')
            attempt += 1
            guess = guess = int(input('Enter a number from 1 through 100: '))

    print()
    print('Congrats! You got it in', attempt, 'guesses!')


# --------------------------------------------------
if __name__ == '__main__':
    main()
